name: end-to-end tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  compile-examples:
    name: compile examples
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: Setup OPAM
      run: sudo apt install opam && opam init && opam install ocamlbuild menhir ounit

    - name: make compile
      run: eval $(opam config env) && make compile

    - name: make examples
      run: eval $(opam config env) && make examples

    - name: share examples
      uses: actions/upload-artifact@v1
      with:
        name: compiled_examples
        path: ./examples

  download-dafny:
    name: download dafny
    needs: compile-examples
    runs-on: ubuntu-latest

    steps:
    - name: download dafny
      run: wget -O ./dafny.zip "https://github.com/dafny-lang/dafny/releases/download/v2.3.0/dafny-2.3.0.10506-x64-win.zip"

    - name: unzip dafny
      run: sudo apt install unzip && unzip dafny.zip

    - name: share dafny folder
      uses: actions/upload-artifact@v1
      with:
        name: dafny
        path: ./dafny

  run-dafny:
    name: run dafny
    needs: download-dafny
    runs-on: windows-latest

    steps:
      - name: get examples
        uses: actions/download-artifact@v1
        with:
          name: compiled_examples

      - name: get dafny
        uses: actions/download-artifact@v1
        with:
          name: dafny

      - name: verify 'helloise'
        run: dafny/dafny /compile 0 compiled_examples/helloise.dfy

      - name: verify 'sparse_vector'
        run: dafny/dafny /compile 0 compiled_examples/sparse_vector.dfy

      - name: verify 'numerical_sparse_vector'
        run: dafny/dafny /compile 0 compiled_examples/numerical_sparse_vector.dfy

      - name: verify 'gap_sparse_vector'
        run: dafny/dafny /compile 0 compiled_examples/gap_sparse_vector.dfy

#      - name: verify 'partial_sum'
#        run: dafny/dafny /compile 0 compiled_examples/partial_sum.dfy

#      - name: verify 'smart_sump'
#        run: dafny/dafny /compile 0 compiled_examples/smart_sum.dfy

  clean-artifacts:
    name: clean up artifacts
    runs-on: ubuntu-latest
    needs: run-dafny
    timeout-minutes: 10

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 second'
        skip-tags: true
        skip-recent: 1
